-- Migration 0005: field_metadata — cap description at 1000 chars, add synopsis (200 chars)
-- Safe to run once on Railway Postgres after 0003 (and 0004 if applicable).
-- Second transaction: one UPDATE per field_name (description and synopsis set to the same literals on each row).

BEGIN;

-- Was TEXT (unlimited); now VARCHAR(1000). Longer existing values are truncated via LEFT().
ALTER TABLE field_metadata
  ALTER COLUMN description TYPE VARCHAR(1000)
  USING LEFT(COALESCE(description, ''), 1000)::VARCHAR(1000);

ALTER TABLE field_metadata
  ADD COLUMN IF NOT EXISTS synopsis VARCHAR(200);

COMMIT;

BEGIN;

UPDATE field_metadata SET description = 'Think of this like a Social Security Number for a bank. The FDIC Certificate ID is a unique number assigned to each depository institution by the Federal Deposit Insurance Corporation. It never changes for the life of the institution, so even if a bank changes its name or gets acquired, researchers can still track its history using the same CERT number. If you ever want to look up a specific bank in FDIC data, this is the most reliable identifier to use.', synopsis = 'A unique ID number the FDIC gives every insured bank.' WHERE field_name = 'cert';
UPDATE field_metadata SET description = 'This is the last day of the financial reporting period. All the financial figures in a bank''s FDIC record — assets, loans, deposits, income — represent the bank''s condition as of this specific date. Banks report quarterly (March 31, June 30, September 30, December 31), so Report Date (REPDTE) tells you which snapshot in time you''re looking at.', synopsis = 'The date the financial data was reported as of.' WHERE field_name = 'repdte';

UPDATE field_metadata SET description = 'Total Assets is the sum of all assets owned by the institution, including cash, loans, securities, bank premises, and other assets. This total does not include off-balance-sheet accounts. In plain terms, imagine emptying out a bank''s entire financial "backpack" — all the cash it holds, every loan it''s issued, every building it owns, every investment it''s made. Add it all up, and you get Total Assets. This is one of the most common ways to measure how big a bank is. JPMorgan Chase, for example, has over $3 trillion in assets.', synopsis = 'Everything the bank owns, added up.' WHERE field_name = 'asset';
UPDATE field_metadata SET description = 'Total Deposits is the sum of all deposits including demand deposits, money market deposits, other savings deposits, time deposits, and deposits in foreign offices. This is essentially all the money people and businesses have trusted the bank to hold — your checking account balance, savings account, CDs, and money market accounts all count. The "foreign offices" part means this number includes deposits held at branches outside the US, making it a truly global picture of the bank''s deposit base.', synopsis = 'All the money customers have deposited at the bank, everywhere in the world.' WHERE field_name = 'dep';
UPDATE field_metadata SET description = 'This is the sum of all domestic office deposits, including demand deposits, money market deposits, other savings deposits, and time deposits. This is the US-only version of the total deposits field above (DEP). For most community banks and credit unions that don''t have international branches, Deposits in Domestic Offices and Total Deposits will be identical. For large global banks like Citibank or HSBC, there will be a notable difference. Comparing Deposits in Domestic Offices to Total Deposits tells you how much of a bank''s business is domestic vs. international.', synopsis = 'All deposits held at US-based branches only.' WHERE field_name = 'depdom';
UPDATE field_metadata SET description = 'This is total equity capital on a consolidated basis. It includes the non-controlling (minority) interests in consolidated subsidiaries. Think of equity like the equity in a house: if your home is worth $400,000 but you owe $300,000 on your mortgage, your equity is $100,000. Similarly, a bank''s equity is what remains after subtracting everything it owes (like customer deposits and borrowed money) from everything it owns (assets). A healthy equity cushion means a bank can absorb losses without collapsing — regulators watch this number very closely.', synopsis = 'The bank''s net worth — what''s left for owners after all debts are subtracted.' WHERE field_name = 'eqtot';
UPDATE field_metadata SET description = 'Banks issue mortgages, auto loans, business loans, credit cards, and equipment leases — Net Loans and Leases is the total of all of these, but with a deduction called the "allowance for loan and lease losses." That deduction is essentially the bank''s honest estimate of how much of what it lent out it may never get back. Loans and leases represent the largest single asset category on the banking industry balance sheet. So Net Loans and Leases is one of the most important numbers for understanding what a bank actually does day-to-day — it reflects the bank''s core business of lending.', synopsis = 'All the money the bank has lent out, minus an estimated buffer for loans that might go bad.' WHERE field_name = 'lnlsnet';
UPDATE field_metadata SET description = 'Not everything a bank owns makes money. A bank branch building doesn''t earn interest — but loans, securities, and certain cash balances do. Earning assets are those income-generating assets. Earning assets include interest-bearing balances, total loans and leases net of unearned income, trading assets, held-to-maturity securities, available-for-sale securities, and federal funds sold. The higher this number relative to total assets, the more efficiently a bank is putting its resources to work. Analysts use it to calculate metrics like Net Interest Margin — basically, how much profit a bank squeezes from every dollar of earning assets.', synopsis = 'All the assets the bank holds that are actively generating income.' WHERE field_name = 'earna';
UPDATE field_metadata SET description = 'This is similar to Net Loans and Leases (LNLSNET) but with two key differences: it''s limited to US branch offices only (no international), and it''s a gross figure — meaning it hasn''t been reduced by the allowance for expected losses. Loans in domestic offices are reported net of unearned income but without any deduction for loss allowances. If you''re trying to understand how much actual lending activity a bank is doing on American soil — mortgages, car loans, small business loans — this is the number to look at. For banks without foreign branches, this will closely match Net Loans and Leases.', synopsis = 'All the loans and leases issued from the bank''s US branches, before subtracting any loss reserve.' WHERE field_name = 'ilndom';
UPDATE field_metadata SET description = 'This is total cash and balances due from depository institutions, including both interest-bearing and noninterest-bearing balances. Banks don''t just hold cash in a vault — they also keep money parked at the Federal Reserve and other banks, sometimes earning interest on it. This field captures all of it. Think of it as the bank''s "liquid savings account." A higher Cash and Balances (CHBAL) means the bank has more immediately available funds, which is a sign of short-term stability. After events like the 2008 financial crisis or COVID, you can see Cash and Balances figures spike as banks got more cautious and held onto more cash.', synopsis = 'Cash on hand plus money the bank is owed by other banks.' WHERE field_name = 'chbal';

UPDATE field_metadata SET description = 'A Money Market Deposit Account (MMDA) is a type of savings account that typically earns a higher interest rate than a standard savings account, but may require a higher minimum balance and can limit how often you withdraw. This field captures the total dollar value of all such accounts held at the bank. Think of it as the "premium savings tier" — customers who park larger amounts here get better rates, and the bank gets a relatively stable pool of funds to work with.', synopsis = 'Deposits held in money market accounts.' WHERE field_name = 'dpmmd';
UPDATE field_metadata SET description = 'This is the total of all traditional savings accounts — the basic accounts most people open at a bank, like a standard savings account you might set up with $25 as a teenager. MMDAs are deliberately excluded here so analysts can separate plain-vanilla savings from premium savings products. This field, combined with DPPMD, gives a complete picture of how much a bank holds in savings-type deposits overall.', synopsis = 'Money held in regular savings accounts, not counting money market accounts.' WHERE field_name = 'dpsav';
UPDATE field_metadata SET description = 'A "transaction account" is any account that lets you move money freely — checking accounts, NOW accounts (interest-bearing checking), and demand deposits all qualify. Unlike savings accounts that are meant to sit and grow, these accounts are the ones connected to your debit card or used to pay bills. BRTTRANS captures the total of all such accounts at the bank''s US branches. Banks closely watch this because transaction accounts represent their most liquid liabilities — customers can withdraw these funds at any time.', synopsis = 'All deposits in accounts that customers can actively transact from, held at US branches.' WHERE field_name = 'brttrans';
UPDATE field_metadata SET description = 'This field narrows transaction accounts to three specific depositor types: individuals (everyday consumers), partnerships (like two friends who own a business together), and corporations (companies of any size). It excludes deposits from government entities, other banks, and foreign institutions. For most community banks, this number represents the vast bulk of their customer base — the businesses and people in their neighborhood who write checks, use debit cards, and pay suppliers out of these accounts.', synopsis = 'Transaction account balances held by regular people, small businesses, and companies.' WHERE field_name = 'p2215';

UPDATE field_metadata SET description = 'When you swipe your credit card and don''t pay the full balance at month''s end, that unpaid amount becomes a loan the bank is carrying on your behalf. LNCRCD is the total of all such outstanding balances — money individuals owe the bank through credit card usage. Banks like Chase, Capital One, and Discover have enormous LNCRCD figures because credit cards are their primary business. For most community banks, this number is small or even zero.', synopsis = 'Total credit card balances that individuals owe to the bank.' WHERE field_name = 'lncrcd';
UPDATE field_metadata SET description = 'This is the combined total of every loan the bank has made where real property (a home, an apartment building, a commercial property, raw land) serves as collateral. It includes everything from the 30-year mortgage your neighbor took out to the $5 million loan a developer used to build a strip mall. Real estate loans are typically the single largest category on a bank''s loan portfolio, and their quality is a key indicator of how exposed the bank is to downturns in the housing or commercial property market.', synopsis = 'All loans secured by real estate — the bank''s total mortgage-related lending.' WHERE field_name = 'lnre';
UPDATE field_metadata SET description = 'These are loans that businesses take out to run and grow their operations — think a restaurant chain borrowing to buy equipment, a manufacturer taking out a line of credit to cover payroll during a slow quarter, or a startup funding its first inventory purchase. Unlike real estate loans (which have property as collateral), C&I loans are often secured by business assets like equipment or receivables, or are unsecured entirely. The size of a bank''s C&I portfolio tells you a lot about how commercially oriented it is versus being primarily a mortgage lender.', synopsis = 'Loans made to businesses for operational needs, not backed by real estate.' WHERE field_name = 'lnci';
UPDATE field_metadata SET description = 'This is the subset of total real estate loans (LNRE) that covers only residential properties — single-family homes, condos, townhouses, and multi-unit residential buildings. It includes both mortgages for people buying homes and home equity loans/lines of credit. This is often the largest single loan type at community banks and savings institutions, and its performance is closely watched after what happened during the 2008 housing crisis, when mass defaults on residential mortgages triggered a global financial meltdown.', synopsis = 'Loans specifically secured by homes and other residential properties.' WHERE field_name = 'lnresre';

UPDATE field_metadata SET description = 'Banks make money primarily by lending — and every loan they issue generates interest payments. This is the total of all interest the bank collected across the year: interest on mortgages, business loans, credit cards, car loans, and even interest earned on securities and cash parked at the Federal Reserve. It''s the top-line revenue number for a bank''s core business. A bank earning more interest income means it''s growing its loan book or interest rates have risen, or both.', synopsis = 'All the money the bank earned from charging interest.' WHERE field_name = 'intinc';
UPDATE field_metadata SET description = 'Banks don''t just receive interest — they also pay it. When you earn 4% on your savings account or CD, that''s money flowing out of the bank. Total Interest Expense captures all such payments: interest paid on savings accounts, CDs, money market accounts, and money the bank borrowed wholesale from other institutions. In a rising interest rate environment, banks'' Total Interest Expense rises as they need to pay more to attract and retain deposits. Subtracting INTEXP from INTINC gives you net interest income — the bank''s core profit margin.', synopsis = 'All the money the bank paid out in interest — to depositors and creditors.' WHERE field_name = 'intexp';
UPDATE field_metadata SET description = 'Not everything a bank earns comes from interest. Non interest income captures income from sources like service charges on deposit accounts, ATM fees, wire transfer fees, wealth management and investment advisory services, mortgage origination fees, and trading revenue. Higher noninterest income is a key driver of bank net income growth FDIC, particularly when interest rates are low and banks can''t rely as heavily on lending spreads. For large banks like Wells Fargo or Goldman Sachs, noninterest income is a huge proportion of total revenue.', synopsis = 'Money the bank earned from fees and services, not from lending.' WHERE field_name = 'nonii';
UPDATE field_metadata SET description = 'This is the bank''s overhead: salaries, bonuses, building leases, technology systems, compliance and legal costs, marketing, insurance, and more. Running thousands of branches, employing tens of thousands of people, and maintaining the IT infrastructure to process millions of transactions is enormously expensive. Non Interest Expense (NONIX) is also called the "efficiency ratio" denominator — the lower a bank''s noninterest expense relative to its revenue, the more efficiently it''s operating. Higher noninterest expense is one of the primary drags on bank net income.', synopsis = 'The bank''s operating costs — everything it costs to run the bank besides paying interest.' WHERE field_name = 'nonix';
UPDATE field_metadata SET description = 'Net income is net interest income plus total noninterest income plus realized gains or losses on securities and extraordinary items, less total noninterest expense, loan loss provisions, and income taxes. In plain English, it''s the bank''s profit after paying its staff, funding its buildings, setting aside reserves for bad loans, and settling up with the IRS. This is the single number that tells you whether a bank made money that year. A healthy, well-run community bank typically generates a net income equal to roughly 1% of its total assets.', synopsis = 'The bank''s bottom-line profit — what''s left after all expenses, losses, and taxes.' WHERE field_name = 'netinc';
UPDATE field_metadata SET description = 'This is a subset of noninterest income (NONII) — specifically the fees banks charge customers for things like overdraft protection, monthly account maintenance, insufficient fund (NSF) charges, paper statement fees, and minimum balance violations. These fees have come under heavy scrutiny in recent years, with many major banks like Bank of America and Chase eliminating overdraft fees under public and regulatory pressure. A bank with a high SC figure relative to its deposit base is leaning heavily on fee income from its own customers.', synopsis = 'Fees the bank collected from customers for deposit account-related services.' WHERE field_name = 'sc';

UPDATE field_metadata SET description = 'ROA is one of the most widely used measures of bank profitability. It''s calculated as net income divided by average total assets, expressed as a percentage. The banking industry''s ROA for full-year 2025 was 1.20 percent. Think of it this way: a bank with $10 billion in assets and a 1% ROA earns $100 million in profit. A higher ROA means the bank is squeezing more profit out of the same pool of assets — a sign of efficiency and smart management. Below 1% is generally considered weak; above 1.5% is excellent for a bank.', synopsis = 'How much profit the bank generates for every dollar of assets it holds.' WHERE field_name = 'roa';
UPDATE field_metadata SET description = 'This is the pre-tax version of ROA — useful for comparing banks across different tax situations, because tax benefits, deferred tax assets, and special tax credits can significantly distort after-tax profitability. For example, a bank holding a lot of municipal bonds (which generate tax-exempt income) might look less profitable on an after-tax ROA basis than it truly is. ROAPTX strips out that noise. The FDIC regularly reports the pretax ROA for banks as a benchmark — the quarterly pretax ROA at community banks was 1.35 percent in Q4 2025. ', synopsis = 'Same as ROA, but before income taxes are subtracted.' WHERE field_name = 'roaptx';
UPDATE field_metadata SET description = 'Net interest margin (NIM) measures the difference between the interest income generated by bank lending and investment and the interest expense incurred from bank borrowing activities, normalized by average earning assets. FDIC In simple terms, if a bank earns 6% on its loans but pays 2% to depositors and creditors, its NIM is roughly 4%. The NIM is more useful than raw net interest income for measuring the profitability of a bank''s primary activities because the denominator focuses strictly on assets that generate income rather than the entire asset base. FDIC The industry''s NIM in Q4 2025 was 3.39 percent, the highest level since 2019.', synopsis = 'The bank''s profit spread between what it earns on loans vs. what it pays on deposits.' WHERE field_name = 'nimy';

UPDATE field_metadata SET description = 'A "noncurrent" loan is one where the borrower is 90 or more days past due, or has stopped making payments entirely (nonaccrual status). Non Current Loan Ratio (ELNATR) expresses that problem loan pool as a percentage of total loans. If a bank''s ELNATR is 1%, it means 1 cent of every dollar it lent is in serious trouble. During normal economic times, this ratio is typically below 1% for healthy banks. During the 2008-2009 financial crisis, it spiked above 5% industry-wide. Watching this ratio trend upward is often an early warning sign before a bank gets into deeper trouble.', synopsis = 'The share of the bank''s loans that borrowers are seriously behind on — a key stress indicator.' WHERE field_name = 'elnatr';
UPDATE field_metadata SET description = 'Equity capital includes preferred and common stock, surplus, and undivided profits. Fdic The equity capital ratio expresses total equity as a percentage of total assets. A bank with $1 billion in assets and $100 million in equity has a 10% equity ratio. The higher this ratio, the more financial cushion the bank has to absorb losses before depositors are at risk. Regulators require banks to maintain minimum equity ratios — banks falling below regulatory minimums face restrictions, and those that fall far enough can be seized and closed.', synopsis = 'The share of the bank''s assets that are funded by the bank''s own money, not debt.' WHERE field_name = 'eq';
UPDATE field_metadata SET description = 'Not all capital is equal in regulators'' eyes. Tier 1 capital is the most reliable form — it consists primarily of common stock and retained earnings, the money that would absorb losses first if the bank ran into serious trouble. Capital requirements based on risk-weighted assets determine how much capital is required based on the riskiness of the bank''s assets, with capital requirements contributing to the safety of the banking system. Regulators require banks to hold Tier 1 capital above a minimum threshold (currently 6% of risk-weighted assets for most banks) as a non-negotiable safety requirement. A bank with a high RBCT is a more robustly cushioned institution.', synopsis = 'The bank''s highest-quality capital — the core financial buffer regulators require to protect against collapse.' WHERE field_name = 'rbct';
UPDATE field_metadata SET description = 'Banks hold many types of assets with very different risk profiles. A US Treasury bond is nearly risk-free; a loan to a startup with no collateral is quite risky. Risk-weighted assets (RWAJ) account for this: each asset is assigned a "risk weight" (0% for Treasuries, up to 100%+ for speculative assets), and those weights are applied before summing everything up. Capital requirements based on risk-weighted assets base how much capital is required on the riskiness of the bank''s assets, while leverage requirements are based on total assets irrespective of riskiness. RWAJ is essentially the denominator in the Tier 1 Capital ratio — the larger a bank''s risky lending, the higher its RWAJ, and the more capital it''s required to hold.', synopsis = 'The bank''s assets adjusted for how risky each one is — the denominator used in capital adequacy calculations.' WHERE field_name = 'rbcrwaj';
UPDATE field_metadata SET description = 'Banks know that some percentage of what they lend will never come back — some borrowers will default. Rather than wait for that to happen, banks proactively set aside a reserve called the allowance for loan and lease losses. Think of it like a rainy day fund specifically for bad loans. This reserve reduces the bank''s reported asset value but provides a buffer against future charge-offs. Regulators scrutinize Allowance for Loan and Lease Losses (LNATRES) carefully — a bank that sets aside too little is either overconfident or trying to inflate its profits artificially. After the 2008 crisis, many banks were criticized for not building this reserve fast enough.', synopsis = 'The amount the bank has set aside as a reserve for loans it expects won''t be fully repaid.' WHERE field_name = 'lnatres';

UPDATE field_metadata SET description = 'This counts the bank''s total workforce, converting part-time employees into full-time equivalents. For example, two half-time tellers count as one full-time equivalent. This is useful for comparing the operational scale of banks — a bank with $50 billion in assets and 500 employees is running very lean (likely tech-forward or focused on wholesale banking), while one with the same assets and 10,000 employees is running a large branch-heavy retail operation. Analysts use Number of Full-Time Employees (NUMEMP) to calculate revenue or assets per employee as an efficiency measure.', synopsis = 'How many people work at the bank, measured in full-time equivalents.' WHERE field_name = 'numemp';
UPDATE field_metadata SET description = 'Number of Domestic Offices (OFFDOM) is the number of domestic offices, including headquarters, operated by active institutions in the 50 states of the USA. Every branch, including the main headquarters, counts. JPMorgan Chase has over 5,000 domestic offices; a local community bank might have just one. Tracking this field over time reveals whether a bank is expanding by opening branches or contracting by closing them — a trend that''s been especially visible as many banks have shut physical locations in favor of digital banking over the past decade.', synopsis = 'How many physical locations the bank operates in the US.' WHERE field_name = 'offdom';

COMMIT;
